application: instawork
version: 2
runtime: python
api_version: 1

inbound_services:
- xmpp_message

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /admin/.*
  script: main.py
  login: admin

- url: /queue/.*
  script: main.py
  login: admin

- url: /go/.*|/done/.*
  login: required
  script: main.py

- url: .*
  script: main.py
